/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as NsiaRouteImport } from './routes/nsia'
import { Route as MembreRouteImport } from './routes/membre'
import { Route as FormulesRouteImport } from './routes/formules'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DelegueRouteImport } from './routes/delegue'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as AssociationsRouteImport } from './routes/associations'
import { Route as AssociationRouteImport } from './routes/association'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminQuartiersRouteImport } from './routes/admin.quartiers'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminNsiaRouteImport } from './routes/admin.nsia'
import { Route as AdminMembresRouteImport } from './routes/admin.membres'
import { Route as AdminDossiersRouteImport } from './routes/admin.dossiers'
import { Route as AdminCotisationsRouteImport } from './routes/admin.cotisations'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAssociationsRouteImport } from './routes/admin.associations'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const NsiaRoute = NsiaRouteImport.update({
  id: '/nsia',
  path: '/nsia',
  getParentRoute: () => rootRouteImport,
} as any)
const MembreRoute = MembreRouteImport.update({
  id: '/membre',
  path: '/membre',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulesRoute = FormulesRouteImport.update({
  id: '/formules',
  path: '/formules',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegueRoute = DelegueRouteImport.update({
  id: '/delegue',
  path: '/delegue',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationsRoute = AssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationRoute = AssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuartiersRoute = AdminQuartiersRouteImport.update({
  id: '/admin/quartiers',
  path: '/admin/quartiers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin/parametres',
  path: '/admin/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNsiaRoute = AdminNsiaRouteImport.update({
  id: '/admin/nsia',
  path: '/admin/nsia',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembresRoute = AdminMembresRouteImport.update({
  id: '/admin/membres',
  path: '/admin/membres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDossiersRoute = AdminDossiersRouteImport.update({
  id: '/admin/dossiers',
  path: '/admin/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCotisationsRoute = AdminCotisationsRouteImport.update({
  id: '/admin/cotisations',
  path: '/admin/cotisations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssociationsRoute = AdminAssociationsRouteImport.update({
  id: '/admin/associations',
  path: '/admin/associations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/association': typeof AssociationRoute
  '/associations': typeof AssociationsRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/delegue': typeof DelegueRoute
  '/faq': typeof FaqRoute
  '/formules': typeof FormulesRoute
  '/membre': typeof MembreRoute
  '/nsia': typeof NsiaRoute
  '/verification': typeof VerificationRoute
  '/admin/associations': typeof AdminAssociationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/dossiers': typeof AdminDossiersRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/nsia': typeof AdminNsiaRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/quartiers': typeof AdminQuartiersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/association': typeof AssociationRoute
  '/associations': typeof AssociationsRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/delegue': typeof DelegueRoute
  '/faq': typeof FaqRoute
  '/formules': typeof FormulesRoute
  '/membre': typeof MembreRoute
  '/nsia': typeof NsiaRoute
  '/verification': typeof VerificationRoute
  '/admin/associations': typeof AdminAssociationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/dossiers': typeof AdminDossiersRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/nsia': typeof AdminNsiaRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/quartiers': typeof AdminQuartiersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/association': typeof AssociationRoute
  '/associations': typeof AssociationsRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/connexion': typeof ConnexionRoute
  '/contact': typeof ContactRoute
  '/delegue': typeof DelegueRoute
  '/faq': typeof FaqRoute
  '/formules': typeof FormulesRoute
  '/membre': typeof MembreRoute
  '/nsia': typeof NsiaRoute
  '/verification': typeof VerificationRoute
  '/admin/associations': typeof AdminAssociationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/dossiers': typeof AdminDossiersRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/nsia': typeof AdminNsiaRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/quartiers': typeof AdminQuartiersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/association'
    | '/associations'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/delegue'
    | '/faq'
    | '/formules'
    | '/membre'
    | '/nsia'
    | '/verification'
    | '/admin/associations'
    | '/admin/audit'
    | '/admin/cotisations'
    | '/admin/dossiers'
    | '/admin/membres'
    | '/admin/nsia'
    | '/admin/parametres'
    | '/admin/quartiers'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/association'
    | '/associations'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/delegue'
    | '/faq'
    | '/formules'
    | '/membre'
    | '/nsia'
    | '/verification'
    | '/admin/associations'
    | '/admin/audit'
    | '/admin/cotisations'
    | '/admin/dossiers'
    | '/admin/membres'
    | '/admin/nsia'
    | '/admin/parametres'
    | '/admin/quartiers'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/association'
    | '/associations'
    | '/comment-ca-marche'
    | '/connexion'
    | '/contact'
    | '/delegue'
    | '/faq'
    | '/formules'
    | '/membre'
    | '/nsia'
    | '/verification'
    | '/admin/associations'
    | '/admin/audit'
    | '/admin/cotisations'
    | '/admin/dossiers'
    | '/admin/membres'
    | '/admin/nsia'
    | '/admin/parametres'
    | '/admin/quartiers'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AssociationRoute: typeof AssociationRoute
  AssociationsRoute: typeof AssociationsRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  ConnexionRoute: typeof ConnexionRoute
  ContactRoute: typeof ContactRoute
  DelegueRoute: typeof DelegueRoute
  FaqRoute: typeof FaqRoute
  FormulesRoute: typeof FormulesRoute
  MembreRoute: typeof MembreRoute
  NsiaRoute: typeof NsiaRoute
  VerificationRoute: typeof VerificationRoute
  AdminAssociationsRoute: typeof AdminAssociationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCotisationsRoute: typeof AdminCotisationsRoute
  AdminDossiersRoute: typeof AdminDossiersRoute
  AdminMembresRoute: typeof AdminMembresRoute
  AdminNsiaRoute: typeof AdminNsiaRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminQuartiersRoute: typeof AdminQuartiersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nsia': {
      id: '/nsia'
      path: '/nsia'
      fullPath: '/nsia'
      preLoaderRoute: typeof NsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membre': {
      id: '/membre'
      path: '/membre'
      fullPath: '/membre'
      preLoaderRoute: typeof MembreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formules': {
      id: '/formules'
      path: '/formules'
      fullPath: '/formules'
      preLoaderRoute: typeof FormulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegue': {
      id: '/delegue'
      path: '/delegue'
      fullPath: '/delegue'
      preLoaderRoute: typeof DelegueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/associations': {
      id: '/associations'
      path: '/associations'
      fullPath: '/associations'
      preLoaderRoute: typeof AssociationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association': {
      id: '/association'
      path: '/association'
      fullPath: '/association'
      preLoaderRoute: typeof AssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quartiers': {
      id: '/admin/quartiers'
      path: '/admin/quartiers'
      fullPath: '/admin/quartiers'
      preLoaderRoute: typeof AdminQuartiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nsia': {
      id: '/admin/nsia'
      path: '/admin/nsia'
      fullPath: '/admin/nsia'
      preLoaderRoute: typeof AdminNsiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/membres': {
      id: '/admin/membres'
      path: '/admin/membres'
      fullPath: '/admin/membres'
      preLoaderRoute: typeof AdminMembresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dossiers': {
      id: '/admin/dossiers'
      path: '/admin/dossiers'
      fullPath: '/admin/dossiers'
      preLoaderRoute: typeof AdminDossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cotisations': {
      id: '/admin/cotisations'
      path: '/admin/cotisations'
      fullPath: '/admin/cotisations'
      preLoaderRoute: typeof AdminCotisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/associations': {
      id: '/admin/associations'
      path: '/admin/associations'
      fullPath: '/admin/associations'
      preLoaderRoute: typeof AdminAssociationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AssociationRoute: AssociationRoute,
  AssociationsRoute: AssociationsRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  ConnexionRoute: ConnexionRoute,
  ContactRoute: ContactRoute,
  DelegueRoute: DelegueRoute,
  FaqRoute: FaqRoute,
  FormulesRoute: FormulesRoute,
  MembreRoute: MembreRoute,
  NsiaRoute: NsiaRoute,
  VerificationRoute: VerificationRoute,
  AdminAssociationsRoute: AdminAssociationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCotisationsRoute: AdminCotisationsRoute,
  AdminDossiersRoute: AdminDossiersRoute,
  AdminMembresRoute: AdminMembresRoute,
  AdminNsiaRoute: AdminNsiaRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminQuartiersRoute: AdminQuartiersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
