/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminQuartiersRouteImport } from './routes/admin.quartiers'
import { Route as AdminMembresRouteImport } from './routes/admin.membres'
import { Route as AdminDossiersRouteImport } from './routes/admin.dossiers'
import { Route as AdminCotisationsRouteImport } from './routes/admin.cotisations'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuartiersRoute = AdminQuartiersRouteImport.update({
  id: '/admin/quartiers',
  path: '/admin/quartiers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembresRoute = AdminMembresRouteImport.update({
  id: '/admin/membres',
  path: '/admin/membres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDossiersRoute = AdminDossiersRouteImport.update({
  id: '/admin/dossiers',
  path: '/admin/dossiers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCotisationsRoute = AdminCotisationsRouteImport.update({
  id: '/admin/cotisations',
  path: '/admin/cotisations',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verification': typeof VerificationRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/dossiers': typeof AdminDossiersRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/quartiers': typeof AdminQuartiersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verification': typeof VerificationRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/dossiers': typeof AdminDossiersRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/quartiers': typeof AdminQuartiersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/verification': typeof VerificationRoute
  '/admin/cotisations': typeof AdminCotisationsRoute
  '/admin/dossiers': typeof AdminDossiersRoute
  '/admin/membres': typeof AdminMembresRoute
  '/admin/quartiers': typeof AdminQuartiersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verification'
    | '/admin/cotisations'
    | '/admin/dossiers'
    | '/admin/membres'
    | '/admin/quartiers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verification'
    | '/admin/cotisations'
    | '/admin/dossiers'
    | '/admin/membres'
    | '/admin/quartiers'
  id:
    | '__root__'
    | '/'
    | '/verification'
    | '/admin/cotisations'
    | '/admin/dossiers'
    | '/admin/membres'
    | '/admin/quartiers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VerificationRoute: typeof VerificationRoute
  AdminCotisationsRoute: typeof AdminCotisationsRoute
  AdminDossiersRoute: typeof AdminDossiersRoute
  AdminMembresRoute: typeof AdminMembresRoute
  AdminQuartiersRoute: typeof AdminQuartiersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quartiers': {
      id: '/admin/quartiers'
      path: '/admin/quartiers'
      fullPath: '/admin/quartiers'
      preLoaderRoute: typeof AdminQuartiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/membres': {
      id: '/admin/membres'
      path: '/admin/membres'
      fullPath: '/admin/membres'
      preLoaderRoute: typeof AdminMembresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dossiers': {
      id: '/admin/dossiers'
      path: '/admin/dossiers'
      fullPath: '/admin/dossiers'
      preLoaderRoute: typeof AdminDossiersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cotisations': {
      id: '/admin/cotisations'
      path: '/admin/cotisations'
      fullPath: '/admin/cotisations'
      preLoaderRoute: typeof AdminCotisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VerificationRoute: VerificationRoute,
  AdminCotisationsRoute: AdminCotisationsRoute,
  AdminDossiersRoute: AdminDossiersRoute,
  AdminMembresRoute: AdminMembresRoute,
  AdminQuartiersRoute: AdminQuartiersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
